language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install -r dev_requirements.txt
script:
  - coverage run setup.py test
  - flake8 .
after_success:
  coveralls
notifications:
  email:
    - pritish.chakraborty@openlabs.co.in
